### ISSUE TITLE
远程搜索remoteMethod方法中的resolve([])方法无效

### ISSUE THREAD

**Issue by brian4159** [jyj1202/vue-lazy-cascader#2]
resolve返回的数组没显示，好像是被原生的filterable覆盖，远程搜索无效

**Comment by jyj1202** [comment]
> resolve返回的数组没显示，好像是被原生的filterable覆盖，远程搜索无效
抱歉我没有复现，可以提供下重新示例吗

**Comment by jyj1202** [comment]
> resolve返回的数组没显示，好像是被原生的filterable覆盖，远程搜索无效

抱歉我没有复现，可以提供下重新示例吗

**Comment by jyj1202** [comment]
> resolve返回的数组没显示，好像是被原生的filterable覆盖，远程搜索无效

没有复现，可以提供下重现示例吗

**Comment by jyj1202** [comment]
> filterable

![image](https://github.com/user-attachments/assets/e9ed46ed-eab6-4b85-b2a5-0d249d825228)
![image](https://github.com/user-attachments/assets/ea7ed47f-ab45-472e-ba6e-ff6e4d29cd67)
看下这两个有没有

![image](https://github.com/user-attachments/assets/f4e24d1e-0123-41f6-b296-283a7400537d)

**Comment by jyj1202** [comment]
> resolve返回的数组没显示，好像是被原生的filterable覆盖，远程搜索无效

![image](https://github.com/user-attachments/assets/e9ed46ed-eab6-4b85-b2a5-0d249d825228)
![image](https://github.com/user-attachments/assets/ea7ed47f-ab45-472e-ba6e-ff6e4d29cd67)
看下这两个有没有

![image](https://github.com/user-attachments/assets/f4e24d1e-0123-41f6-b296-283a7400537d)
